// app/layout.tsx (or in your `pages/_app.tsx` if you're using the pages directory)
import { Inter } from "next/font/google";
import Head from "next/head";  // Import the next/head component
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Crypto Tracking Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Head>
          {/* Global Meta Tags */}
          <meta name="robots" content="index, follow" />
          <meta
            name="description"
            content="Explore Figma Design tools and track cryptocurrency in one platform. Join our growing community of designers and crypto enthusiasts."
          />
          <meta
            name="keywords"
            content="Figma design, crypto tracking, design platform, cryptocurrency, design tools, Figma tools"
          />

          {/* Open Graph Meta Tags */}
          <meta property="og:title" content="Figma Design Platform - Crypto Tracking and Design Tools" />
          <meta property="og:description" content="Explore Figma Design tools and track cryptocurrency in one platform." />
          <meta property="og:url" content="https://figma-design001.vercel.app" />
          <meta property="og:site_name" content="Figma Design Platform" />
          <meta property="og:image" content="https://figma-design001.vercel.app/images/preview-image.jpg" />
          <meta property="og:type" content="website" />
          <meta property="og:image:width" content="1200" />
          <meta property="og:image:height" content="630" />

          {/* Twitter Meta Tags */}
          <meta name="twitter:card" content="summary_large_image" />
          <meta name="twitter:title" content="Figma Design Platform - Crypto Tracking and Design Tools" />
          <meta name="twitter:description" content="Explore Figma Design tools and track cryptocurrency in one platform." />
          <meta name="twitter:image" content="https://figma-design001.vercel.app/images/preview-image.jpg" />
        </Head>
        <div className="bg-[#060C22]">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
